services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    env_file:
      - ./api/.env
    container_name: laravel_api
    working_dir: /var/www/html
    volumes:
      - ./api:/var/www/html
      - ./api/docker/php.ini:/usr/local/etc/php/php.ini
    networks:
      - laravel
    deploy:
      resources:
        limits:
          cpus: 0.50
          memory: 512M
        reservations:
          cpus: 0.25
          memory: 128M

  nginx:
    env_file:
      - ./api/.env
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./api:/var/www/html
      - ./api/docker/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
    networks:
      - laravel
    depends_on:
      - api
    deploy:
      resources:
        limits:
          cpus: 0.50
          memory: 512M
        reservations:
          cpus: 0.25
          memory: 128M

  db:
    image: mysql:8.0
    container_name: db
    restart: unless-stopped
    env_file:
      - ./api/.env
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - laravel
    deploy:
      resources:
        limits:
          cpus: 0.50
          memory: 512M
        reservations:
          cpus: 0.25
          memory: 128M

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: unless-stopped
    env_file:
      - ./api/.env
    links:
      - db
    ports:
      - 8081:80
    networks:
      - laravel
    deploy:
      resources:
        limits:
          cpus: 0.50
          memory: 512M
        reservations:
          cpus: 0.25
          memory: 128M

networks:
  laravel:

volumes:
  db-data:
